# Generated by Django 4.0.5 on 2022-06-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('co_author', models.CharField(max_length=30)),
                ('date_of_creation', models.DateField()),
                ('is_loan', models.BooleanField(default=False)),
                ('date_checkout', models.DateTimeField()),
                ('data_return', models.DateTimeField()),
                ('loan_time', models.DateTimeField()),
            ],
        ),
    ]
