# Generated by Django 4.0.5 on 2022-06-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Book'},
        ),
        migrations.RenameField(
            model_name='books',
            old_name='date_of_creation',
            new_name='registration_date',
        ),
        migrations.AddField(
            model_name='books',
            name='member',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='data_return',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='date_checkout',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='loan_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
