# Generated by Django 4.0.5 on 2022-06-30 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_books_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='registration_date',
            field=models.DateField(default=datetime.date(2022, 6, 30)),
        ),
    ]
