# Generated by Django 4.0.5 on 2022-07-01 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_books_author_alter_books_co_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='registration_date',
            field=models.DateField(default=datetime.date(2022, 7, 1)),
        ),
    ]
