# Generated by Django 4.0.5 on 2022-07-02 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_books_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='registration_date',
            field=models.DateField(default=datetime.date(2022, 7, 2)),
        ),
    ]
