# Generated by Django 4.0.5 on 2022-07-02 23:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_books_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 2, 23, 44, 52, 507241, tzinfo=utc)),
        ),
    ]
